const MAGIC_STICKER_ID = "CgACAgQAAxkBAAIChmQkInYaNPGzJ6u4_B3xH-fa4-_RAAIOAwACl2MEU3-lr3Md1yF1LwQ";
const NOT_CLEAR_STICKER_ID = "CgACAgQAAxkBAAIF8mR0dtv_1dzSKwv7cYXB-AeRqdQNAAIwAwACKoYEU84MWTuHJz_3LwQ";
const PLEASE_STICKER_ID = "CgACAgQAAxkBAAIF_2R0d8owU_ClzMWGEcgu_3UXE0nMAAIIAwACZhINU06sKPiYKep_LwQ";
const ERROR_STICKER_ID = "CgACAgQAAxkBAAIGGWR0eWo5jkxZEVS7KKuFyMjGNv-hAAMDAAKffwVTXBuaQHl2l40vBA";

export { MAGIC_STICKER_ID, NOT_CLEAR_STICKER_ID, PLEASE_STICKER_ID, ERROR_STICKER_ID };
